#!/usr/bin/env python3
# PROFILE_AND_OPTIMIZE_OPT_OUT: internal module; tools/ai_tuning/ai_tuning.py remains the canonical CLI.
"""Local helpers for LLM-assisted MLPerf tuning.

The commands in this file are intentionally offline: they inspect artifacts,
validate proposals, and materialize derived files, but they do not submit Slurm
jobs or mutate cluster state.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path
from typing import Any

from tools.ai_tuning.optimizer import gp as gp_engine
from tools.ai_tuning.optimizer import hyp_format, hyp_session
from tools.ai_tuning.optimizer import hyperband as hb_engine
from tools.ai_tuning.optimizer import tpe as tpe_engine

REPO_ROOT = Path(__file__).resolve().parents[2]
from tools.shared.jsonutil import load_json

DEFAULT_SPACE = REPO_ROOT / "tuning" / "tuning-space.b200-llama31-8b.json"

# Safety constants live in a small sibling module so reviewers can audit
# the forbidden-pattern table and ledger-status enum without paging
# through the full tuner CLI. Re-exports preserve backwards compat for
# callers that still import these names from this module.
from tools.ai_tuning.helpers import (
    _build_optimizer_space,
    _experiment_state_value,
    _objective_direction,
    _observations_from_states,
    _resolve_hyperband_config,
    append_jsonl,
    candidate_key,
    candidate_seen,
    choose_objective,
    finite_parameter_domains,
    iter_candidate_parameters,
    latest_experiment_states,
    objective_catalog,
    read_ledger_records,
    utc_timestamp,
    write_json,
)
from tools.ai_tuning.safety import (
    EXPERIMENT_LEDGER_SCHEMA_VERSION,
    PROPOSAL_SCHEMA_VERSION,
)


def command_optimizer_propose(args: argparse.Namespace) -> int:
    space = load_json(Path(args.space))
    selected_objective = choose_objective(space, args.objective)
    objective = (
        str(selected_objective.get("name"))
        if isinstance(selected_objective, dict)
        else "mlperf_submission_readiness"
    )
    direction = _objective_direction(space, objective)
    domains = finite_parameter_domains(space)
    selected_domains = [
        domain for domain in domains if not args.parameter or domain["name"] in set(args.parameter)
    ]
    if not selected_domains:
        raise SystemExit("optimizer propose requires at least one finite parameter domain")
    selected_names = [domain["name"] for domain in selected_domains]

    records = read_ledger_records(args.ledger) if args.ledger else []
    states = latest_experiment_states(records)
    rng = random.Random(args.seed)

    strategy = args.strategy
    variant = args.variant
    candidates: list[dict[str, Any]] = []
    optimizer_state: dict[str, Any] = {
        "strategy": strategy,
        "objective": objective,
        "selected_parameters": selected_names,
        "ledger": str(args.ledger) if args.ledger else None,
    }
    total_possible: int | None = None
    truncated_default = False

    if strategy in {"deterministic_matrix", "random"}:
        total_possible, parameter_iterator = iter_candidate_parameters(
            selected_domains, strategy, rng
        )
        for parameters in parameter_iterator:
            if candidate_seen(parameters, states):
                continue
            candidates.append(
                {
                    "parameters": parameters,
                    "objective": objective,
                    "priority": len(candidates) + 1,
                    "rationale": f"Generated by optimizer strategy {strategy}.",
                    "risk": "Candidate still requires proposal validation and operator review before cluster submission.",
                }
            )
            if len(candidates) >= args.limit:
                break
        optimizer_state["seed"] = args.seed if strategy == "random" else None
        truncated_default = len(candidates) < (total_possible or 0)
    elif strategy == "bayesian":
        try:
            optimizer_space = _build_optimizer_space(space, selected_names)
        except ValueError as exc:
            raise SystemExit(str(exc)) from exc
        observations = _observations_from_states(optimizer_space, states)
        skip = {candidate_key({str(k): str(v) for k, v in record.get("parameters", {}).items()}) for record in states.values() if isinstance(record.get("parameters"), dict)}
        engine_variant = variant or "tpe"
        if engine_variant == "tpe":
            decoded, engine_state = tpe_engine.propose(
                optimizer_space,
                observations,
                direction,
                rng,
                limit=args.limit,
                candidate_pool=max(args.limit * 4, 16),
                skip_keys=skip,
            )
        elif engine_variant == "gp":
            decoded, engine_state = gp_engine.propose(
                optimizer_space,
                observations,
                direction,
                rng,
                limit=args.limit,
                candidate_pool=max(args.limit * 8, 32),
                skip_keys=skip,
            )
        else:
            raise SystemExit(f"unknown bayesian variant {engine_variant!r}; expected tpe or gp")
        for params in decoded:
            candidates.append(
                {
                    "parameters": params,
                    "objective": objective,
                    "priority": len(candidates) + 1,
                    "rationale": f"Generated by Bayesian optimizer ({engine_variant}).",
                    "risk": "Bayesian candidates still require proposal validation and operator review.",
                }
            )
        optimizer_state.update(engine_state)
    elif strategy == "multifidelity":
        try:
            optimizer_space = _build_optimizer_space(space, selected_names)
        except ValueError as exc:
            raise SystemExit(str(exc)) from exc
        observations = _observations_from_states(optimizer_space, states)
        skip = {candidate_key({str(k): str(v) for k, v in record.get("parameters", {}).items()}) for record in states.values() if isinstance(record.get("parameters"), dict)}
        engine_variant = variant or "hyperband"
        config = _resolve_hyperband_config(space, engine_variant, args)
        state_in = None
        if args.state_file is not None:
            path = Path(args.state_file)
            if not path.is_file():
                raise SystemExit(f"missing optimizer state file: {path}")
            state_in = load_json(path)
        decoded, engine_state = hb_engine.propose(
            optimizer_space,
            observations,
            direction,
            rng,
            config=config,
            variant=engine_variant,
            state_in=state_in,
            skip_keys=skip,
        )
        for entry in decoded:
            params = entry["parameters"] if isinstance(entry, dict) else entry
            fidelity = entry.get("fidelity") if isinstance(entry, dict) else None
            candidate = {
                "parameters": params,
                "objective": objective,
                "priority": len(candidates) + 1,
                "rationale": f"Generated by multi-fidelity optimizer ({engine_variant}).",
                "risk": "Multi-fidelity candidates still require proposal validation and operator review.",
            }
            if fidelity is not None:
                candidate["fidelity"] = fidelity
            candidates.append(candidate)
        optimizer_state.update(engine_state)
        state_out = args.state_out or args.state_file
        if state_out is not None:
            write_json(hb_engine.advance_rung(engine_state), Path(state_out))
    else:
        raise SystemExit(f"unknown strategy {strategy!r}")

    payload = {
        "schema_version": PROPOSAL_SCHEMA_VERSION,
        "tuning_space_id": space.get("id"),
        "generated_by": f"tools/ai_tuning/ai_tuning.py optimizer propose --strategy {strategy}",
        "total_possible_candidates": total_possible,
        "truncated": truncated_default,
        "optimizer_state": optimizer_state,
        "candidates": candidates,
    }
    write_json(payload, args.output)
    return 0

def command_optimizer_status(args: argparse.Namespace) -> int:
    space = load_json(Path(args.space))
    objectives = objective_catalog(space)
    contracts = space.get("config_mutation_contracts", [])
    optimizer_block = space.get("optimizer", {}) if isinstance(space.get("optimizer"), dict) else {}
    fidelity_block = space.get("fidelity") if isinstance(space.get("fidelity"), dict) else None

    available_strategies = ["deterministic_matrix", "random", "bayesian", "multifidelity"]
    bayesian_variants = ["tpe", "gp"]
    multifidelity_variants = ["hyperband", "bohb"]

    contracts_implemented = {
        "objective_scoring": bool(objectives),
        "structured_result_ingestion": True,
        "config_mutation_contracts": bool(contracts),
        "repeatability_noise_handling": True,
        "mlperf_legality_gates": True,
        "optimizer_state": True,
    }
    optimizer_capabilities = {
        "tpe_landed": True,
        "gp_landed": True,
        "hyperband_landed": True,
        "bohb_landed": True,
        "hyp_template_import_landed": True,
        "hyp_session_import_landed": True,
        "real_session_validation": "deferred to next PR",
        "empirical_comparison_against_hypertune": "deferred to next PR",
        "multi_objective_pareto": "future",
    }

    payload = {
        "schema_version": 1,
        "tuning_space": {
            "path": str(Path(args.space)),
            "id": space.get("id"),
            "parameter_count": len(space.get("parameters", [])),
        },
        "contracts_implemented": contracts_implemented,
        "objectives": objectives,
        "config_mutation_contracts": contracts,
        "optimizer_config": optimizer_block,
        "fidelity": fidelity_block,
        "available_strategies": available_strategies,
        "bayesian_variants": bayesian_variants,
        "multifidelity_variants": multifidelity_variants,
        "optimizer_capabilities": optimizer_capabilities,
    }
    write_json(payload, args.output)
    return 0

def command_optimizer_history(args: argparse.Namespace) -> int:
    space = load_json(Path(args.space)) if args.space else {}
    records = read_ledger_records(args.ledger)
    states = latest_experiment_states(records)
    grouped: dict[str, list[dict[str, Any]]] = {}
    for record in states.values():
        objective = str(record.get("objective") or "unknown")
        if args.objective and objective != args.objective:
            continue
        value = _experiment_state_value(record)
        entry = {
            "experiment_id": record.get("experiment_id"),
            "status": record.get("status"),
            "parameters": record.get("parameters", {}),
            "fidelity": record.get("fidelity"),
            "result_value": value,
            "optimizer_state": {
                "strategy": (record.get("optimizer_state") or {}).get("strategy")
                if isinstance(record.get("optimizer_state"), dict)
                else None,
                "variant": (record.get("optimizer_state") or {}).get("variant")
                if isinstance(record.get("optimizer_state"), dict)
                else None,
            },
        }
        grouped.setdefault(objective, []).append(entry)

    objective_summaries = []
    for objective, experiments in sorted(grouped.items()):
        direction = _objective_direction(space, objective) if space else "maximize"
        scored = [item for item in experiments if item["result_value"] is not None]
        unscored = [item for item in experiments if item["result_value"] is None]
        scored.sort(
            key=lambda item: float(item["result_value"]),
            reverse=(direction == "maximize"),
        )
        experiments = scored + unscored
        objective_summaries.append(
            {
                "objective": objective,
                "direction": direction,
                "experiment_count": len(experiments),
                "experiments": experiments[: args.limit],
                "truncated": len(experiments) > args.limit,
            }
        )

    payload = {
        "schema_version": 1,
        "ledger": str(args.ledger),
        "objectives": objective_summaries,
    }
    write_json(payload, args.output)
    return 0

def command_optimizer_compare(args: argparse.Namespace) -> int:
    space = load_json(Path(args.space))
    records = read_ledger_records(args.ledger)
    states = latest_experiment_states(records)
    record_a = states.get(args.experiment_a)
    record_b = states.get(args.experiment_b)
    if record_a is None:
        raise SystemExit(f"unknown experiment id: {args.experiment_a}")
    if record_b is None:
        raise SystemExit(f"unknown experiment id: {args.experiment_b}")

    objective_name = args.objective or record_a.get("objective") or record_b.get("objective") or "mlperf_submission_readiness"
    direction = _objective_direction(space, objective_name)

    value_a = _experiment_state_value(record_a)
    value_b = _experiment_state_value(record_b)

    winner: str | None = None
    delta: float | None = None
    if value_a is not None and value_b is not None:
        delta = value_a - value_b
        if delta == 0:
            winner = "tie"
        elif direction == "maximize":
            winner = args.experiment_a if value_a > value_b else args.experiment_b
        else:
            winner = args.experiment_a if value_a < value_b else args.experiment_b

    legality_changed = (
        record_a.get("config_patches") != record_b.get("config_patches")
    )

    payload = {
        "schema_version": 1,
        "objective": objective_name,
        "direction": direction,
        "experiment_a": {
            "experiment_id": args.experiment_a,
            "status": record_a.get("status"),
            "parameters": record_a.get("parameters"),
            "result_value": value_a,
            "fidelity": record_a.get("fidelity"),
            "config_patches": record_a.get("config_patches"),
        },
        "experiment_b": {
            "experiment_id": args.experiment_b,
            "status": record_b.get("status"),
            "parameters": record_b.get("parameters"),
            "result_value": value_b,
            "fidelity": record_b.get("fidelity"),
            "config_patches": record_b.get("config_patches"),
        },
        "metric_deltas": {
            "result_value_delta": delta,
        },
        "winner": winner,
        "legality_gates_changed": legality_changed,
    }
    write_json(payload, args.output)
    return 0

def command_optimizer_import_hyp(args: argparse.Namespace) -> int:
    template_path = Path(args.template)
    if not template_path.is_file():
        raise SystemExit(f"missing .hyp template: {template_path}")
    parameters = hyp_format.parse_file(template_path)
    manifest_parameters = hyp_format.to_manifest_parameters(parameters)

    payload: dict[str, Any] = {
        "schema_version": 1,
        "template": str(template_path),
        "parsed_parameters": [
            {
                "name": param.name,
                "kind": param.kind,
                "minimum": param.minimum,
                "maximum": param.maximum,
                "values": param.values,
                "flag_token": param.flag_token,
            }
            for param in parameters
        ],
        "manifest_parameters": manifest_parameters,
    }

    if args.write_space:
        if not manifest_parameters:
            raise SystemExit("cannot write imported tuning space: no hypertune markers found in template")
        out_space = {
            "schema_version": 1,
            "id": args.imported_space_id or f"imported-from-{template_path.stem}",
            "description": f"Tuning space imported from hypertune template {template_path.name}",
            "target": {"benchmark": args.target_benchmark or "imported"},
            "parameters": manifest_parameters,
        }
        write_json(out_space, Path(args.write_space))
        payload["space_path"] = str(args.write_space)

    if args.session_dir:
        session_path = Path(args.session_dir)
        if not session_path.is_dir():
            raise SystemExit(f"missing session directory: {session_path}")
        parameter_names = {param["name"] for param in manifest_parameters}
        session = hyp_session.import_session(session_path, parameter_names)
        objective = session.objective or args.default_objective
        payload["session"] = {
            "session_id": session.session_id,
            "objective": objective,
            "trial_count": len(session.trials),
        }
        if args.ledger:
            ledger_path = Path(args.ledger)
            ledger_path.parent.mkdir(parents=True, exist_ok=True)
            for trial in session.trials:
                shape = {"benchmark": args.target_benchmark or "imported"}
                record = {
                    "schema_version": EXPERIMENT_LEDGER_SCHEMA_VERSION,
                    "event": "created",
                    "timestamp": utc_timestamp(),
                    "experiment_id": f"hyp-{trial.trial_id[:12]}",
                    "status": trial.status,
                    "tuning_space_id": payload.get("space_path") or template_path.stem,
                    "shape": shape,
                    "parameters": trial.parameters,
                    "objective": objective,
                    "provenance": "hyp_import",
                    "result_value": trial.score,
                    "trial_metadata": {
                        "session_id": session.session_id,
                        "trial_id": trial.trial_id,
                        "sbatch_file": trial.sbatch_file,
                        "log_file": trial.log_file,
                    },
                    "owner": "hyp_import",
                    "priority": 1000,
                }
                append_jsonl(ledger_path, record)
            payload["ledger_records_written"] = len(session.trials)
            payload["ledger"] = str(ledger_path)

    write_json(payload, args.output)
    return 0
