"""portability_view: the lever-by-model portability matrix.

``value_view`` answers "what are our levers + what do we grind next"; ``fleet_leaderboard``
answers "which model do I pick". Neither answers the cross-question an operator actually
asks when a NEW model is brought up (or when deciding what to roll to staging/prod): "which
of our PROVEN levers should I try on THIS model, and which were already refuted on it?".

This verb renders that lever (row) x model (column) matrix from the curated
``value-findings.yaml`` registry's ``validated_on`` / ``candidate_on`` / ``refuted_on``
fields, plus a per-model "try-next" candidate list (the actionable deploy/test queue per
model). Dependency-light: reads only the small registry dict (no pyarrow / matplotlib), so
it runs in a minimal install. Added in profile-and-optimize (perf_tune_report portability_view verb).
"""
from __future__ import annotations

from typing import Any

VALIDATED, CANDIDATE, REFUTED, UNTESTED = "validated", "candidate", "refuted", "untested"
_GLYPH = {VALIDATED: "Y", CANDIDATE: "~", REFUTED: "X", UNTESTED: "."}
_MODEL_KEYS = ("validated_on", "candidate_on", "refuted_on")


def collect_models(registry: dict) -> list[str]:
    """The union of model tokens named across every finding's validated/candidate/refuted
    lists (these are real model names; ``applies_to`` is a scope label, not a column)."""
    models: set[str] = set()
    for f in registry.get("findings", []):
        for k in _MODEL_KEYS:
            for m in (f.get(k) or []):
                if isinstance(m, str) and m.strip():
                    models.add(m.strip())
    return sorted(models)


def cell_state(finding: dict, model: str) -> str:
    """State of one (lever, model) cell. refuted > validated > candidate > untested:
    a model that BOTH lost and was a candidate reads as refuted (the measured verdict wins)."""
    if model in (finding.get("refuted_on") or []):
        return REFUTED
    if model in (finding.get("validated_on") or []):
        return VALIDATED
    if model in (finding.get("candidate_on") or []):
        return CANDIDATE
    return UNTESTED


def build_portability(registry: dict) -> dict[str, Any]:
    """Build the matrix view: models (columns), one row per finding that names >=1 model,
    and the per-model candidate (try-next) lists."""
    models = collect_models(registry)
    rows: list[dict[str, Any]] = []
    for f in registry.get("findings", []):
        if not any(f.get(k) for k in _MODEL_KEYS):
            continue  # a finding that names no model has nothing to place on the matrix
        rows.append({
            "id": f.get("id", ""),
            "title": f.get("title", ""),
            "applies_to": str(f.get("applies_to", "") or ""),
            "lifecycle": f.get("lifecycle", "?"),
            "next_value": str(f.get("next_value", "med") or "med").lower(),
            "states": {m: cell_state(f, m) for m in models},
        })
    candidates: dict[str, list[str]] = {m: [] for m in models}
    for r in rows:
        for m in models:
            if r["states"][m] == CANDIDATE:
                candidates[m].append(r["id"])
    return {"models": models, "rows": rows, "candidates": candidates}


def render_markdown(view: dict, *, title: str = "Lever x model portability matrix") -> str:
    models = view["models"]
    lines = [
        f"# {title} (generated by `perftunereport portability_view`)",
        "",
        f"Legend: `{_GLYPH[VALIDATED]}` validated (measured) | `{_GLYPH[CANDIDATE]}` candidate "
        f"(try next) | `{_GLYPH[REFUTED]}` refuted (measured to lose / not apply) | "
        f"`{_GLYPH[UNTESTED]}` untested.",
        "",
        "> Rows = perf levers (`value-findings.yaml`); columns = fleet models. Read a column "
        "top-to-bottom to see which proven levers to try on that model. The cells are the "
        "single source of truth from each finding's validated_on / candidate_on / refuted_on.",
        "",
        "| lever | applies_to | " + " | ".join(models) + " |",
        "| --- | --- | " + " | ".join(["---"] * len(models)) + " |",
    ]
    for r in view["rows"]:
        cells = " | ".join(_GLYPH[r["states"][m]] for m in models)
        lines.append(f"| {r['id']} | {r['applies_to'] or '-'} | {cells} |")
    lines += ["", "## Try-next by model (candidate levers to deploy / test)", ""]
    cand = view["candidates"]
    if any(cand[m] for m in models):
        for m in models:
            if cand[m]:
                lines.append(f"- **{m}**: " + ", ".join(cand[m]))
    else:
        lines.append("- (none) -- every model's levers are validated or refuted; no open candidates.")
    lines.append("")
    return "\n".join(lines)
